/*const data = {
  status: "success",
  items: [
      {
          id: 1,
          title: "Collar rombo",
          price: 25000,
          image: require("./images/Collares/collarrombo.jpeg"),
          category: "Collares",
          cantidad: 0,
          img1: "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img",
          img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
      },
      {
          id: 2,
          title: "Collar ovalado",
          price: 25000,
          image: require("./images/Collares/collarovalado.jpeg"),
          category: "Collares",
          cantidad: 0,
          img1: "https://stockx-360.imgix.net/Nike-Dunk-Low-Off-White-Pine-Green/Images/Nike-Dunk-Low-Off-White-Pine-Green/Lv2/img",
          img2: ".jpg?auto=format,compress&q=90&updated_at=1606319825&w=1000",
      },
      {
          id: 3,
          title: "Collar gota",
          price: 25000,
          image: require("./images/Collares/collargota.jpeg"),
          category: "Collares",
          cantidad: 0,
      },
      {
          id: 4,
          title: "Collar ovalado violeta",
          price: 25000,
          image: require("./images/Collares/collarovaladovioleta.jpeg"),
          category: "Collares",
          cantidad: 0,
      },
      {
          id: 5,
          title: "Combo collar circular + aretes",
          price: 40000,
          image: require("./images/Combos/combocolllarcircular.jpeg"),
          category: "Combo",
          cantidad: 0,
      },
      {
          id: 6,
          title: "Aretes circulares",
          price: 20000,
          image: require("./images/Aretes/aretescirculares.jpeg"),
          category: "Aretes",
          cantidad: 0,
      },
      {
          id: 7,
          title: "Combo collar pentagono + aretes",
          price: 40000,
          image: require("./images/Combos/combocollarpentagono.jpeg"),
          category: "Combo",
          cantidad: 0,
      },
      {
          id: 8,
          title: "Collar circular rosado",
          price: 25000,
          image: require("./images/Collares/collarcircularrosado.jpeg"),
          category: "Collares",
          cantidad: 0,
      },
      {
          id: 9,
          title: "Collar corazón",
          price: 25000,
          image: require("./images/Collares/collarcorazon.jpeg"),
          category: "Collares",
          cantidad: 0,
      },
      {
          id: 10,
          title: "Combo collar púrpura + aretes",
          price: 25000,
          image: require("./images/Combos/combocollarpurpura.jpeg"),
          category: "Combo",
          cantidad: 0,
      },
  ],
};

export default data; */
